[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
anyhow = "1.0.0"
tokio = { version = "1.0.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
